### ISSUE TITLE
Have searchString accept arrays

### ISSUE THREAD

**Issue by itsjustluck** [benkeen/grunt-search#6]
I was hoping to use this in a project, but I need to search for a large set of data in an array rather than a single string or regex.

**Comment by benkeen** [comment]
Interesting! So if you could define an array of strings/regexps for the `searchString` field, would that work for you?

```javascript
        short_tags: {
            files: {
                src: ["**/*.php"]
            },
            options: {
                searchString: [
                  /(<\?[^p])|(<\?$)/,
                  "a string"
               ]
                logFormat: "console"
            }
        },
```

**Comment by itsjustluck** [comment]
Yes, a string or regex  in an array would be perfect! I have a list of pngs that I want to check if they being used anywhere in an application.

**Comment by benkeen** [comment]
Hey @itsjustluck - I just released 0.1.7 that allows you to include an array of strings/regexps. Mind giving it a go? If you have any problems with it, just raise a ticket. :)

**Comment by itsjustluck** [comment]
I've been taking a look at it. It's really slow. :-/ 

It's a really big query. I'm look for ways to lighten the load. I'm thinking about using Cheerio to thin out my search to just src and style attributes.

**Comment by benkeen** [comment]
Cool! And yeah, there are definitely improvements that could be made to this repo too - speed-wise, I mean.
